// Graph Layout Settings
export const GRAPH_LAYOUT = {
  PADDING_VERTICAL: 50,
  PADDING_HORIZONTAL: 50,
  WITHOUT_ROOT_PADDING_VERTICAL: 5,
  WITHOUT_ROOT_PADDING_HORIZONTAL: 5,
  NODE_MARGIN_VERTICAL: 15,
  NODE_MARGIN_HORIZONTAL: 25,
  GROUP_NODE_PADDING_VERTICAL: 15,
  CHOICE_PADDING_HORIZONTAL: 25,
  CHOICE_PADDING_VERTICAL: 10,
}

// Graph Node Dimensions
export const GRAPH_NODE = {
  FONT_SIZE: 16,
  PADDING_VERTICAL: 2,
  PADDING_HORIZONTAL: 10,
  BORDER_RADIUS: 5,
  MIN_WIDTH: 20,
  MIN_HEIGHT: 26,
}

// Graph Specific Dimensions
export const GRAPH_DIMENSIONS = {
  ROOT_RADIUS: 5,
  ICON_SIZE: 18,
  QUANTIFIER_MEASURE_HEIGHT: 16,
  NAME_MEASURE_HEIGHT: 16,
  QUANTIFIER_TEXT_FONTSIZE: 14,
  NAME_TEXT_FONTSIZE: 14,
  QUOTE_PADDING: 2,
}

// Computed Graph Dimensions
export const GRAPH_COMPUTED = {
  QUANTIFIER_HEIGHT: Math.max(
    GRAPH_DIMENSIONS.QUANTIFIER_TEXT_FONTSIZE * 1.5,
    GRAPH_DIMENSIONS.ICON_SIZE,
  ),
  NAME_HEIGHT: Math.max(
    GRAPH_DIMENSIONS.NAME_TEXT_FONTSIZE * 1.5,
    GRAPH_DIMENSIONS.ICON_SIZE,
  ),
}

// graph
export const GRAPH_TEXT_FONT_SIZE = 16
export const GRAPH_NODE_PADDING_VERTICAL = 2
export const GRAPH_NODE_PADDING_HORIZONTAL = 10
export const GRAPH_NODE_BORDER_RADIUS = 5
export const GRAPH_NODE_MARGIN_VERTICAL = 15
export const GRAPH_NODE_MARGIN_HORIZONTAL = 25
export const GRAPH_GROUP_NODE_PADDING_VERTICAL = 15
export const GRAPH_CHOICE_PADDING_HORIZONTAL = 25
export const GRAPH_CHOICE_PADDING_VERTICAL = 10
export const GRAPH_ROOT_RADIUS = 5
export const GRAPH_NODE_MIN_WIDTH = 20
export const GRAPH_NODE_MIN_HEIGHT = 26
export const GRAPH_ICON_SIZE = 18
export const GRAPH_QUANTIFIER_MEASURE_HEIGHT = 16
export const GRAPH_NAME_MEASURE_HEIGHT = 16
export const GRAPH_QUANTIFIER_TEXT_FONTSIZE = 14
export const GRAPH_NAME_TEXT_FONTSIZE = 14
export const GRAPH_QUANTIFIER_HEIGHT = Math.max(
  GRAPH_QUANTIFIER_TEXT_FONTSIZE * 1.5,
  GRAPH_ICON_SIZE,
)
export const GRAPH_NAME_HEIGHT = Math.max(
  GRAPH_NAME_TEXT_FONTSIZE * 1.5,
  GRAPH_ICON_SIZE,
)
export const GRAPH_QUOTE_PADDING = 2

export const GRAPH_PADDING_VERTICAL = 50
export const GRAPH_PADDING_HORIZONTAL = 50
export const GRAPH_WITHOUT_ROOT_PADDING_VERTICAL = 5
export const GRAPH_WITHOUT_ROOT_PADDING_HORIZONTAL = 5
